### ISSUE TITLE
NMsim installation warning

### ISSUE THREAD

**Issue by akurumaddali** [NMautoverse/NMsim#10] opened 2024-07-01 18:05 UTC
I'm using R 4.1.3 version and as I'm trying to install NMsim, I see the following warning message:

![image](https://github.com/philipdelff/NMsim/assets/97485035/8d4d6383-2ba1-48c0-a1bf-ee04b396d90e)

Any workaround to install NMsim with a older version of R? Thanks.

**Comment by philipdelff** [comment] 2024-07-01 18:18
Thanks,

I can install NMsim from CRAN on R 4.1.1. I would expect it to work on any R version since R 3.5. Could it be you are using a different repository than CRAN?
Try to specify a CRAN repo this way:
install.packages("NMsim",repos="https://cloud.r-project.org")

**Comment by akurumaddali** [comment] 2024-07-01 18:50
Thanks, I tried the above command, here are the errors:

![image](https://github.com/philipdelff/NMsim/assets/97485035/ec458386-fcaf-4940-8c81-c62e7e1f16ff)


![image](https://github.com/philipdelff/NMsim/assets/97485035/c0103402-2a4a-453b-9440-3680bfbcb445)

**Comment by philipdelff** [comment] 2024-07-01 19:15
OK, that worked. Now the issue is that your NMdata also needs to be updated. The easiest will be to restart R and then do:
install.packages("NMsim",repos="https://cloud.r-project.org/")
You can install NMdata first by running both of these two but it shouldn't be necessary:
install.packages("NMdata",repos="https://cloud.r-project.org/")
install.packages("NMsim",repos="https://cloud.r-project.org/")

**Comment by akurumaddali** [comment] 2024-07-01 20:19
The old NMdata package couldn't be removed from the Metworx workflow and hence "NMsim" could not be installed in this workflow despite trying to restart R, using detach and update package functions.
However, upon creating a new metworx workflow, "NMsim 0.1.0" and "NMdata 0.1.6" were successfully installed.

**Comment by philipdelff** [comment] 2024-07-17 18:08
Closing this since it's not related to NMsim.

**Closed as completed by philipdelff** 2024-07-17 18:08 UTC
